version: "3.8"
name: "parcel-delivery"
services:
  keycloak-postgres:
    image: "postgres:16.0"
    volumes:
    - kc_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KC_PG_DB}
      POSTGRES_USER: ${KC_PG_USER}
      POSTGRES_PASSWORD: ${KC_PG_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KC_PG_USER} -d ${KC_PG_DB}"]
      interval: 3s
      timeout: 5s
      retries: 3

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: ${KC_PG_DB}
      DB_USER: ${KC_PG_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${KC_PG_PASSWORD}
      
      KEYCLOAK_ADMIN: ${KC_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_PASSWORD}
    ports:
      - "8080:8080"
    command: ['start-dev']
    depends_on:
      keycloak-postgres:
        condition: service_healthy


volumes:
  kc_db_data:
    name: parcel-delivery-kc-db-data
