apiVersion: skaffold/v3
kind: Config
metadata:
  name: app
build:
  artifacts:
  - image: logistic-service
    context: logistic-service
  # - image: payment-service
  #   context: payment-service
  # - image: parcel-service
  #   context: parcel-service
  # - image: keycloak-service
  #   context: keycloak
  - image: client
    context: client
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: false
manifests:
  rawYaml:
  # - ./k8s/*
    # - ./k8s/keycloak-db.yaml
    # - ./k8s/keylcloak-service.yaml
    - ./k8s/logistic-db.yaml
    - ./k8s/logistic-service.yaml
    - ./k8s/client.yaml
  # TODO: add parcel and payment services
deploy:
  kubectl: {}
