apiVersion: apps/v1
kind: Deployment
metadata:
  name:  keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  keycloak-db
  template:
    metadata:
      labels:
        app:  keycloak-db
    spec:
      containers:
        - name:  keycloak-db
          image: postgres:16.0
          env:
            - name: POSTGRES_DB
              value: parcel-iam-db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
spec:
  selector:
    app:  keycloak-db
  ports:
    - name: tcp
      port: 5432
      targetPort: 5432
