apiVersion: apps/v1
kind: Deployment
metadata:
  name: parcel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parcel-service
  template:
    metadata:
      labels:
        app: parcel-service
    spec:
      containers:
        - name: parcel-service
          image: parcel-service
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: parcel-service
spec:
  selector:
    app: parcel-service
  ports:
    - name: tcp
      port: 3000
      targetPort: 3000
