apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistic-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logistic-db
  template:
    metadata:
      labels:
        app: logistic-db
    spec:
      containers:
        - name: logistic-db
          image: mongo:7.0-rc
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: logistic-db
spec:
  selector:
    app: logistic-db
  ports:
    - name: tcp
      port: 27017
      targetPort: 27017
